### ISSUE TITLE
Test input file of URLs if is empty

### ISSUE THREAD

**Issue by yyan0214** [yyan0214/Article_scraper#2]
Description: This test case checks how the program handles an empty input file, where there are no URLs to process.
Test Input: An empty input file.
Expected Output: The program should gracefully handle the empty input file, possibly by displaying a message indicating that there are no URLs to process. Error message"No URLs found in 'input_file_name'. The file might be empty or contain only whitespace."

**Comment by jbrowbb** [comment]
Using an empty txt file that was placed in Data/raw, the code was able to find that the file was empty adn display the message "Error: No URLs found in 'Data/raw/articles.txt'. The file might be empty or contain only whitespace.". As well as not to proceed to the code that writes the articles and summaries.

**Comment by yyan0214** [comment]
I wrote an empty file to test this part, and it told me "No URLs found in 'Data/raw/empty.txt'. The file might be empty or contain only whitespace." Passed!
