### ISSUE TITLE
Check for existence of URL file before processing

### ISSUE THREAD

**Issue by jbrowbb** [yyan0214/Article_scraper#3]
Double check that the file holding the URLs are in Data/raw, if the file does not exist then write a code that says the file name does not exist

**Comment by yyan0214** [comment]
I finished that. I test for the wrong file name, it will output the error message to tell you.

**Comment by jbrowbb** [comment]
I inputed a file that does not exist one the Data/raw path and it gave the correct error statement of "Error: DAta/raw/articles.txt not found" and exited out of the program
