### ISSUE TITLE
If the URLs are linking to multiple articles

### ISSUE THREAD

**Issue by yyan0214** [yyan0214/Article_scraper#5]
Description: This test case verifies that the program correctly identifies URLs that link to multiple articles, indicating that they likely represent the homepage of a website.
Test Input: A URL representing the homepage of a news website or a website with multiple articles.
Expected Output: The program should recognize the URLs as representing the homepage of a website. And output the error message"Error checking URL status: HTTPSConnectionPool(host='URL-link', port=port-number): Read timed out. (read timeout=5)"

**Comment by jbrowbb** [comment]
When tested for home page, only www.usnews.com/ was able to be skipped, code was unable to skip other single URLs, like www.bbc.com/

**Comment by yyan0214** [comment]
I checked this one with the URL"https://www.usnews.com/".Then it gave me an error message like"Error checking URL status: HTTPSConnectionPool(host='www.usnews.com', port=443): Read timed out. (read timeout=5)" and skipped this URL. I think it passed.
