### ISSUE TITLE
Word Count

### ISSUE THREAD

**Issue by jbrowbb** [yyan0214/Article_scraper#7]
Test if summary's word count is the required number word count

**Comment by yyan0214** [comment]
I finished it, you will get the counts for every summary file.

**Comment by jbrowbb** [comment]
When ran, the article summaries meet the word count. Assuming they read the prompt for being its minimum word count, not the maximum word count. This is without the title being included in the word count.

It could also with the word count going after the given number is because the code reads the title and additional titles to separate data
