### ISSUE TITLE
URLs with content behind authentication walls

### ISSUE THREAD

**Issue by yyan0214** [yyan0214/Article_scraper#8]
Description: This test case focuses on verifying the behavior of the program when encountering URLs that lead to content behind authentication walls.
Input: URL
output: if this happened, the error message will output.

**Comment by jbrowbb** [comment]
The code is unable to tell if autorization is needed, some URLs don't have identifers that the code can easily tell if authorization is needed. Tried with moodle and blackboard, but got a text file that was read from the URL of how to set up authenication. Only stick to publicly available URLs.

**Comment by yyan0214** [comment]
I test it with this URL"https://api.openai.com/v1/chat/completions". Then it outputs the error message and skips this. I this it passed.
